### ISSUE TITLE
Events emitters on remove hide layers from workspace

### ISSUE THREAD

**Issue by mohamed-benkhalifa** [OntimizeWeb/ontimize-web-ng2-map#6]
I need event emitters when removing or hiding layers from workspace:

`<o-map-workspace #oMapWorkspace flex></o-map-workspace>`

**Comment by gonzalo-martinez-imt** [comment]
'onToggleWSLayerSelected', 'onToggleWSLayerVisibility' and 'onToggleWSLayerInWS' outputs created
